/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application

    java
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")

    // Args4j
    // https://mvnrepository.com/artifact/args4j/args4j
    implementation("args4j:args4j:2.33")
}

application {
    // Define the main class for the application.
    mainClass.set("MML2Audio.Main")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.jar {
    archiveFileName.set("MML2Audio.jar")
    manifest {
        attributes["Main-Class"] = "MML2Audio.Main"
    }
}

tasks.shadowJar {
    archiveBaseName.set("../../../MML2Audio")
    archiveClassifier.set("")
    archiveVersion.set("") 
}